### ISSUE TITLE
​Cannot enable "run at startup as admin" / 无法启用“以管理员身份开机启动”

### ISSUE THREAD

**Issue by JasonWei512** [JasonWei512/EnergyStarX#35]
### Description / 描述

A user reports that he cannot enable "run at startup admin". Unfortunately I cannot reproduce this bug.

有用户报告说他无法启用“以管理员身份开机启动”。不幸的是我没法复现这个 Bug。

### Reproduction steps / 复现步骤

1. Click the "Run at startup as admin" checkbox in settings page.
2. Confirm the UAC prompt.
3. Cannot enable the setting, the checkbox returns to unchecked status.
4. Open Windows's Task Scheduler. Energy Star X should have created a schedule task called "EnergyStarXAdminStartupTask" in Task Scheduler Library, but it didn't.

1. 点击设置页的“以管理员身份开机启动”勾选框。
2. UAC 窗口弹出，点击确认。
3. 启用失败，勾选框变回未勾选状态。
4. 打开 Windows 的任务计划程序。能源之星X 应该会在“任务计划程序库”中创建一个名为 "EnergyStarXAdminStartupTask" 的计划任务，但是它没有。

### Windows version / Windows 版本

Windows 11 22H2 Build 22623.0

### Hardware specs / 硬件配置

机械革命 Mechrevo S2 Air
AMD Ryzen 7 4800H     
16 GB RAM

### Error log / 错误日志

2022/12/29 21:15:55.143 | INFO 丨 Failed to set StartupType to "Admin"

**Comment by TnZzZHlp** [comment]
我也遇到了这个问题,我找到了这个log但是不知道有没有用
`2023-03-22 12:43:52.3207|ERROR|EnergyStarX.App|Unhandled and unrecoverable exception|System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 329
   at H.NotifyIcon.Core.TrayIconWithContextMenu.<Create>b__15_0() in /_/src/libs/H.NotifyIcon/PopupMenus/TrayIconWithContextMenu.cs:line 57
2023-03-22 12:47:25.7010|ERROR|EnergyStarX.App|Unhandled and unrecoverable exception|System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 329
   at H.NotifyIcon.Core.TrayIconWithContextMenu.<Create>b__15_0() in /_/src/libs/H.NotifyIcon/PopupMenus/TrayIconWithContextMenu.cs:line 57
2023-03-22 12:49:44.8845|ERROR|EnergyStarX.App|Unhandled and unrecoverable exception|System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 329
   at H.NotifyIcon.Core.TrayIconWithContextMenu.<Create>b__15_0() in /_/src/libs/H.NotifyIcon/PopupMenus/TrayIconWithContextMenu.cs:line 57
`

**Comment by Keplex** [comment]
我这里内存完整性打开的情况下还是可以勾选以管理员身份启动，系统版本是22H2

**Comment by TnZzZHlp** [comment]
> 我这里内存完整性打开的情况下还是可以勾选以管理员身份启动，系统版本是22H2

那就不知道了，我开了这个内存完整性保护就没法以管理员方式启动了

**Comment by xingjunfeng** [comment]
> 找到问题原因了,开了windows defender的内存保护的话就会出现这个问题,还有请问一下大佬用管理员方式启动会有什么区别么 ![图片](https://user-images.githubusercontent.com/98214647/226805914-2ddb43bc-0c9d-450a-9e98-649520b9e0ca.png) ![图片](https://user-images.githubusercontent.com/98214647/226805959-2f83b4c5-bf54-4577-bc69-db4d71d37378.png)

这个bug是我反馈的，我这个内存完整性是关着的，现在我确认在关闭内存完整性的情况下，仍然无法“以管理员身份启动”
![image](https://user-images.githubusercontent.com/106024601/232667367-bfd06998-4993-4eeb-9982-4c38a1dba1a7.png)

**Comment by Shineblind** [comment]
I had the same problem, Open settings -> Search for "Reset this PC" -> "Fix problems using Windows Update" and hit "Reinstall now" and reinstall the latest update and it should work. this is what it looked like for me before

https://github.com/user-attachments/assets/3cb47baa-ac90-492d-810e-f562d8ef0975

**Comment by xingjunfeng** [comment]
> I had the same problem, Open settings -> Search for "Reset this PC" -> "Fix problems using Windows Update" and hit "Reinstall now" and reinstall the latest update and it should work. this is what it looked like for me before
> 
>  412184200-3d9857fc-d008-4636-a045-f0e40fb2bdfa.mp4

I have tried your method, even more extreme ones, and I have once formatted the computer completely and installed the system myself, but it still didn't work. However, I succeeded on the computer at my workplace once.

**Comment by Shineblind** [comment]
then I might have another solution for you to start it on startup, but it wont get started minimized:

press Windows key + R, type in shell:startup
that opens the startup folder, now press Windows key and search for "Energy Star X", drag the Energy Star X icon to the Startup folder, it might work, or maybe not.

another thing is press Windows key, search for "Energy Star X", right click it and choose "App Settings", and choose "Runs at log-in" (this option wasnt there for me until I run Fix problems using Windows update for some reason and u might have the same problem) 

![Image](https://github.com/user-attachments/assets/1c7ae8cd-f64d-448a-8c44-890b19dfb9f7)

my last option is Windows key + R, type in shell:AppsFolder, find Energy Star X there, create a shortcut of it and place it in shell:startup

**Comment by xingjunfeng** [comment]
> then I might have another solution for you to start it on startup, but it wont get started minimized:
> 
> press Windows key + R, type in shell:startup that opens the startup folder, now press Windows key and search for "Energy Star X", drag the Energy Star X icon to the Startup folder, it might work, or maybe not.
> 
> another thing is press Windows key, search for "Energy Star X", right click it and choose "App Settings", and choose "Runs at log-in" (this option wasnt there for me until I run Fix problems using Windows update for some reason and u might have the same problem)
> 
> ![Image](https://github.com/user-attachments/assets/1c7ae8cd-f64d-448a-8c44-890b19dfb9f7)
> 
> my last option is Windows key + R, type in shell:AppsFolder, find Energy Star X there, create a shortcut of it and place it in shell:startup

You may have misunderstood my question. I'm unable to "start up with administrator privileges at boot", but it can start up at boot with normal user privileges.
