### ISSUE TITLE
The app crashes when the cursor is hovered over it​

### ISSUE THREAD

**Issue by NJinsei** [JasonWei512/EnergyStarX#36]
### Description / 描述

When the app is minimised for a while and the mouse is hovered over it, it cause the app and also seems to cause other UWP apps that are minimised in task to crash as well. (Magicpods)

### Reproduction steps / 复现步骤

1. Have the app be minimised
2. Use the device normally for a few minutes
3. Hover cursor over the task

### Windows version / Windows 版本

Edition	Windows 11 Home Version	22H2 Installed on	‎01/‎10/‎2022 OS build	22621.1105 Experience	Windows Feature Experience Pack 1000.22638.1000.0

### Hardware specs / 硬件配置

Device name	FlowX16
Processor	AMD Ryzen 9 6900HS with Radeon Graphics           3.30 GHz
Installed RAM	32.0 GB (31.3 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

### Error log / 错误日志

2022-11-25 17:48:38.9251|ERROR|EnergyStarX.App|Unhandled and unrecoverable exception|System.InvalidOperationException: UpdateIcon failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateIcon(IntPtr handle) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 359
   at EnergyStarX.Services.SystemTrayIconService.UpdateTrayIconImageAndToolTip()
   at CommunityToolkit.WinUI.DispatcherQueueExtensions.<>c__DisplayClass0_0.<EnqueueAsync>b__1()
--- End of stack trace from previous location ---
   at EnergyStarX.Services.SystemTrayIconService.RunOnUIThread(Action action)
   at EnergyStarX.Services.SystemTrayIconService.EnergyService_StatusChanged(Object sender, EnergyStatus e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2022-11-29 19:23:22.9429|ERROR|EnergyStarX.App|Unhandled and unrecoverable exception|System.InvalidOperationException: UpdateIcon failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateIcon(IntPtr handle) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 359
   at EnergyStarX.Services.SystemTrayIconService.UpdateTrayIconImageAndToolTip()
   at CommunityToolkit.WinUI.DispatcherQueueExtensions.<>c__DisplayClass0_0.<EnqueueAsync>b__1()
--- End of stack trace from previous location ---
   at EnergyStarX.Services.SystemTrayIconService.RunOnUIThread(Action action)
   at EnergyStarX.Services.SystemTrayIconService.EnergyService_StatusChanged(Object sender, EnergyStatus e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2022-12-01 17:52:31.9087|ERROR|EnergyStarX.App|Unhandled and unrecoverable exception|System.InvalidOperationException: UpdateIcon failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateIcon(IntPtr handle) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 359
   at EnergyStarX.Services.SystemTrayIconService.UpdateTrayIconImageAndToolTip()
   at CommunityToolkit.WinUI.DispatcherQueueExtensions.<>c__DisplayClass0_0.<EnqueueAsync>b__1()
--- End of stack trace from previous location ---
   at EnergyStarX.Services.SystemTrayIconService.RunOnUIThread(Action action)
   at EnergyStarX.Services.SystemTrayIconService.EnergyService_StatusChanged(Object sender, EnergyStatus e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2022-12-05 03:29:24.0911|ERROR|EnergyStarX.App|Unhandled and unrecoverable exception|System.InvalidOperationException: UpdateIcon failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateIcon(IntPtr handle) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 359
   at EnergyStarX.Services.SystemTrayIconService.UpdateTrayIconImageAndToolTip()
   at CommunityToolkit.WinUI.DispatcherQueueExtensions.<>c__DisplayClass0_0.<EnqueueAsync>b__1()
--- End of stack trace from previous location ---
   at EnergyStarX.Services.SystemTrayIconService.RunOnUIThread(Action action)
   at EnergyStarX.Services.SystemTrayIconService.EnergyService_StatusChanged(Object sender, EnergyStatus e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2022-12-09 19:10:22.9135|ERROR|EnergyStarX.Services.SystemTrayIconService|Caught exception thrown by trayIcon.UpdateIcon()|System.InvalidOperationException: UpdateIcon failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateIcon(IntPtr handle) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 359
   at EnergyStarX.Services.SystemTrayIconService.UpdateTrayIconImageAndToolTip(Boolean isThrottling)
2022-12-09 19:10:22.9601|ERROR|EnergyStarX.Services.SystemTrayIconService|Caught exception thrown by trayIcon.UpdateToolTip()|System.InvalidOperationException: UpdateToolTip failed.
   at H.NotifyIcon.Core.TrayIcon.UpdateToolTip(String text) in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 335
   at EnergyStarX.Services.SystemTrayIconService.UpdateTrayIconImageAndToolTip(Boolean isThrottling)
2023-01-11 21:24:14.8770|ERROR|EnergyStarX.App|Unhandled and unrecoverable exception|System.InvalidOperationException: TryCreate failed.
   at H.NotifyIcon.Core.TrayIcon.Create() in /_/src/libs/H.NotifyIcon/Core/TrayIcon.cs:line 226
   at H.NotifyIcon.Core.TrayIconWithContextMenu.<Create>b__15_0() in /_/src/libs/H.NotifyIcon/PopupMenus/TrayIconWithContextMenu.cs:line 56

**Comment by JasonWei512** [comment]
Do you mean the system tray icon?
![image](https://user-images.githubusercontent.com/16899918/213638309-82f02b28-a0ee-46bd-b369-eb825aa5918d.png)

Are you using some taskbar enhancement tool like [StartAllBack](https://www.startallback.com/)? 
See: https://github.com/JasonWei512/EnergyStarX/issues/7#issuecomment-1279691880

Are you using the latest version (1.0.4)?

**Comment by l0lGhostlxl** [comment]
I am talking about the system icon, not using any enhancements, and I am using the latest version.

**Comment by JasonWei512** [comment]
Could you record a video?

**Comment by l0lGhostlxl** [comment]
It's difficult to record as when it happens it is quite random but infrequent. But what happens is that as soon as the mouse is hovered over it all UWP apps seem to crash and they disappears from the expanded task bar. Requiring the user to open the app again.
